'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Send,X,Square,Headphones,Volume2,VolumeX} from 'lucide-react';
type Action={reply:string;action:string;productId:string|null};
type Message={role:'user'|'assistant';content:string};
type Recognition={lang:string;interimResults:boolean;onresult:((e:{results:{[key:number]:{[key:number]:{transcript:string}}}})=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
export function Concierge({open,onOpen,currentProduct,onAction}:{open:boolean;onOpen:(b:boolean)=>void;currentProduct:string;onAction:(a:Action)=>void}){
 const [messages,setMessages]=useState<Message[]>([{role:'assistant',content:'Bienvenue chez Africa Parfum. Quel parfum aimeriez-vous découvrir ? Vous pouvez me donner un nom, une marque ou une note que vous aimez.'}]);const [input,setInput]=useState('');const [busy,setBusy]=useState(false);const [listening,setListening]=useState(false);const [error,setError]=useState('');const [connected,setConnected]=useState<boolean|null>(null);const [voice,setVoice]=useState(false);const recognition=useRef<Recognition|null>(null);const request=useRef<AbortController|null>(null);const feed=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(location.hostname.endsWith('github.io')){setConnected(false);return}fetch('/api/concierge').then(r=>r.json() as Promise<{connected:boolean}>).then(d=>setConnected(d.connected)).catch(()=>setConnected(false));return()=>{recognition.current?.abort();request.current?.abort();window.speechSynthesis?.cancel()}},[]);
 useEffect(()=>{feed.current?.scrollTo({top:feed.current.scrollHeight})},[messages,busy]);
 async function ask(value:string,spoken=false){if(busy||!value.trim())return;if(connected===false){setError('La vitrine est disponible en ligne. Pour parler à Hermes, utilisez la démonstration locale : le service vocal public reste à héberger.');return;}recognition.current?.abort();setListening(false);window.speechSynthesis?.cancel();setError('');setInput('');setBusy(true);const history=messages.slice(-6);setMessages(m=>[...m,{role:'user',content:value}]);const controller=new AbortController();request.current=controller;const timer=setTimeout(()=>controller.abort(),65000);
 try{const res=await fetch('/api/concierge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:value,history,currentProduct}),signal:controller.signal});const data=await res.json() as Action & {error?:string};if(!res.ok)throw new Error(data.error||'Hermes est indisponible.');onAction(data);setMessages(m=>[...m,{role:'assistant',content:data.reply}]);if((voice||spoken)&&window.speechSynthesis){const utterance=new SpeechSynthesisUtterance(data.reply);utterance.lang='fr-FR';utterance.rate=1;window.speechSynthesis.speak(utterance)}}catch(e){setError(e instanceof Error&&e.name==='AbortError'?'Conversation interrompue. Vous pouvez réessayer.':e instanceof Error?e.message:'La connexion a échoué.')}finally{clearTimeout(timer);setBusy(false);request.current=null}}
 function mic(){if(listening){recognition.current?.stop();return}const w=window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition};const Constructor=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Constructor){setError('La reconnaissance vocale n’est pas prise en charge ici. Ouvrez la démonstration dans Chrome ou utilisez le texte.');return}window.speechSynthesis?.cancel();const r=new Constructor();r.lang='fr-FR';r.interimResults=false;r.onresult=e=>{const text=e.results[0][0].transcript;void ask(text,true)};r.onerror=e=>{setError(e.error==='not-allowed'?'Le microphone n’est pas autorisé. Autorisez-le dans votre navigateur ou écrivez votre demande.':'Aucune parole reconnue. Réessayez ou utilisez le texte.');setListening(false)};r.onend=()=>setListening(false);recognition.current=r;setVoice(true);setError('');try{r.start();setListening(true)}catch{setError('Le microphone n’a pas pu démarrer.')}}
 function close(){recognition.current?.abort();request.current?.abort();window.speechSynthesis?.cancel();setListening(false);onOpen(false)}
 return <><button className="primary chat-toggle" onClick={()=>open?close():onOpen(true)} aria-expanded={open} aria-controls="hermes-panel"><Headphones size={18}/>{open?'Fermer Hermes':'Votre conseiller Hermes'}</button>{open&&<section className="chat-panel" id="hermes-panel" aria-label="Conversation avec Hermes"><div className="chat-heading"><div><h2>Hermes</h2><p>{connected?'Votre conseiller parfums':'Présentation · Hermes à connecter'}</p></div><button aria-label={voice?'Couper la voix':'Activer la voix'} onClick={()=>{setVoice(v=>!v);window.speechSynthesis?.cancel()}}>{voice?<Volume2 size={17}/>:<VolumeX size={17}/>}</button><button onClick={close} aria-label="Fermer la conversation"><X size={19}/></button></div><div className="messages" ref={feed} role="log" aria-live="polite">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><b>{m.role==='user'?'VOUS':'HERMES'}</b>{m.content}</div>)}{busy&&<p className="message">Hermes prépare votre réponse…</p>}{error&&<p className="message error-text" role="alert">{error}</p>}</div><div className="suggestions"><button disabled={busy} onClick={()=>ask('Montre-moi Sauvage de Dior')}>Voir Sauvage</button><button disabled={busy} onClick={()=>ask('Je cherche un parfum boisé')}>J’aime les boisés</button></div><form className="chat-form" onSubmit={e=>{e.preventDefault();void ask(input)}}><input aria-label="Votre demande à Hermes" placeholder="Un parfum, une envie…" value={input} onChange={e=>setInput(e.target.value)} maxLength={1000} disabled={busy}/><button type="button" onClick={mic} disabled={busy} aria-label={listening?'Arrêter le microphone':'Parler au microphone'}>{listening?<Square size={18}/>:<Mic size={18}/>}</button><button type="submit" aria-label="Envoyer" disabled={busy||!input.trim()}><Send size={18}/></button></form><p className="chat-hint">{listening?'Je vous écoute…':'Le micro démarre uniquement à votre demande. La transcription peut utiliser le service vocal du navigateur.'}</p></section>}</>
}
